### ISSUE TITLE
zlib fails hard instead of retrying

### ISSUE THREAD

**Issue by rgbkrk** [mafintosh/prebuild#103]
I'm running `prebuild` on Windows and scratching my head more than usual.

```
PS C:\Users\Administrator\zmq-prebuilt> prebuild --all
prebuild info begin Prebuild version 4.1.0
prebuild info build Preparing to prebuild zmq-prebuilt@0.0.3 for v0.10.42 on win32-x64 using node-gyp
prebuild http GET https://nodejs.org/dist/v0.10.42/node-v0.10.42-headers.tar.gz
prebuild http 200 https://nodejs.org/dist/v0.10.42/node-v0.10.42-headers.tar.gz
prebuild WARN install got an error, rolling back install
prebuild ERR! install error
prebuild ERR! stack Error: unexpected end of file
prebuild ERR! stack     at Zlib._handle.onerror (zlib.js:363:17)
prebuild ERR! not ok
prebuild ERR! build unexpected end of file
```

Any idea how to extract more logs out of this? `prebuild --compile` works fine

**Comment by hintjens** [comment]
This is the same issue as https://github.com/nodejs/node-gyp/issues/693 IMO. When fetching the node files, there are random failures on the last chunk. It succeeds perhaps 10-20% of the time. Other times you'll get checksum errors, and this error if the code continues to try to unpack the archive.

It works with `prebuild --compile` because you're not fetching anything.

You can reproduce using `node-gyp install` and the simple download script from @klemmster. The fault is presumably in node itself. HTTP fetching should not be failing like this.

**Comment by rgbkrk** [comment]
so very right, thanks for linking the node-gyp issue

I think I can close this as an upstream issue to be solved.
