### ISSUE TITLE
Intended workflow

### ISSUE THREAD

**Issue by mathiask88** [mafintosh/prebuild#104]
Hi,

I want to add prebuild to my node addon and I want to ask if I get the workflow right. If i have a new release ready:
- Create Github release with changelog etc.
- Prebuild the release on all platforms for all ABI versions
- Trigger upload on all platforms to add the release downloads
- Add release to npm

Does prebuild differentiate between armv6 and armv7?

Best regards

**Comment by ralphtheninja** [comment]
> Hi,
> 
> I want to add prebuild to my node addon and I want to ask if I get the workflow right.

Hi! Cool :)

Not sure if you meant the pointed list as the workflow of prebuild or your own workflow, please excuse me if I got that wrong.

> Create Github release with changelog etc.

`prebuild` will create the release on github for you, so need to do that manually. However, there's no support for adding a changelog (at least not yet, haven't thought about if we want to do that or not) so you would have to do that yourself manually (or using the github api I guess).

> Trigger upload on all platforms to add the release downloads

This is also handled by prebuild after the binaries have been built.

> Add release to npm

This is not handled by prebuild so something you have to do with `npm publish`, which also makes sense since you want to be sure the binaries have been built and uploaded to the release on github before you actually publish the new version of your module.

> Does prebuild differentiate between armv6 and armv7?

This is a good question and something that is a bit of an uncharted territory. When I build for `leveldown` (using the rpi2) it will generate binaries of the form `leveldown-v1.4.4-node-v11-linux-arm.tar.gz` (see https://github.com/Level/leveldown/releases/tag/v1.4.4) and this is because node's `process.arch` returns the string `arm`, so it seems node itself doesn't handle that difference.

**Comment by ralphtheninja** [comment]
Ps. I would suggest you just tried and if the arm differences doesn't play out well for you, we'll adjust prebuild until it does.

**Comment by mathiask88** [comment]
Thanks for the fast response and you got it right. I read that prebuild will build and upload the binaries for me and that it obviously does not `npm publish` :) I think I was uncertain about the right use. 

> ...so it seems node itself doesn't handle that difference.
That's right, but node binaries are available for v6, v7 and v8. Maybe performance aspects (instruction sets)?

Although armv8 is backwards compatible to armv5 I think it could be a good addition to differentiate between arm versions, because if I prebuild on armv7 it won't run on armv8 but prebuild will download the arm build. Or is ARM also upwards compatible? I'm not an expert in these things ;)

I think I will use the current solution until somebody cries (unlikely).

**Comment by ralphtheninja** [comment]
@mathiask88 Closing this if you don't mind :)
