### ISSUE TITLE
cannot build offline - always wants to download the headers even if they are in node-gyp's cache

### ISSUE THREAD

**Issue by dominictarr** [mafintosh/prebuild#172]
node-gyp has a cache, but prebuild seems to always want to download the node headers,
if it fails to find a prebuilt version for the library it's installing.

however, I can install offline if I do `npm install sodium-prebuit --ignore-scripts; cd node_modules/sodium-prebuilt; node-gyp rebuild`

so, node-gyp doesn't seem like the problem here

**Comment by juliangruber** [comment]
It seems like we're calling `node-gyp` with `node-gyp rebuild --target=${target} --target-arch=${target-arch}`. I first though we might always be passing the `--dist-url` parameter which could make it always download, but that's not the case. Can you confirm the `node-gyp` binary also doesn't try to download headers when you pass those two `--target` and `--target-arch` parameters?

**Comment by dominictarr** [comment]
Okay, inside sodium-prebuilt i ran `node-gyp rebuild --target=v7.8.0 --arch=x64 --platform=linux` (those where the arguments I saw dumped when I ran `npm install` there, curiously I needed to run `make` first, but I think that is a separate problem.) it did not download any headers.

**Comment by ralphtheninja** [comment]
Afaik it's actually `node-gyp` doing the download of the headers. I don't have the exact details in my head at the moment but I have a vague memory letting node-gyp do that instead of having separate download functionality (which prebuild had before). I can do some digging tomorrow to find out what's going on.

**Comment by ralphtheninja** [comment]
I might also be delirious and simply just rambling so don't take my vague memory too seriously ;)

**Comment by mathiask88** [comment]
The problem is not that node-gyp wants to redownload, but that `node-gyp` downloads the header files into the project directory, because we are using `node-gyp` by requiring it. `node-gyp` only sets the download directory when using the bin file (https://github.com/nodejs/node-gyp/blob/master/bin/node-gyp.js#L25-L37), but we can pass the `--devdir` argument with the default `~/.node-gyp`

**Comment by dominictarr** [comment]
oh thanks @mathiask88 that makes sense

**Comment by ralphtheninja** [comment]
@dominictarr Mind giving me a command you run to reproduce this?

**Comment by mathiask88** [comment]
@ralphtheninja The problem is, if you use `node-gyp` from the CLI it uses the bin file and then sets the download dir there https://github.com/nodejs/node-gyp/blob/master/bin/node-gyp.js#L25-L37 since `3.5.0`. In prebuild we use `node-gyp` by requiring it and then run the commands like the bin file does, but the `devdir` variable is never set, so `prebuild/node-gyp` downloads the header files directly into the project directory.
@dominictarr has all the header files for his node version in `~/.node-gyp / C:\Users\<User>\.node-gyp`, which should be enough, but `prebuild/node-gyp` does not look there because it wants the header files in the project directory.

**Comment by ralphtheninja** [comment]
6.2.1
