### ISSUE TITLE
An example of config for another project

### ISSUE THREAD

**Issue by havenchyk** [mafintosh/prebuild#66]
Hi! I'm wondering how to integrate the prebuild with another project - https://github.com/atom/node-keytar. Could anyone suggest, where to get started?

Also I have a newbie question:
Is the situation the same as for node-pre-gyp, where we need to use "real" windows and linux to build the binary and then store it under the aws?

Sorry if it's not the best place to ask. /cc @ralphtheninja

**Comment by brett19** [comment]
Hey @havenchyk,

The situation is similar in that you need to use windows, linux, mac, etc.. systems (one for each of your target platforms really) to build your binaries.  However, unlike node-pre-gyp, we by default upload and download from GitHub releases files rather than using AWS (although AWS is an option as well using a custom download URI).

The easiest way to get started is to simply run `prebuild` on your systems to do the builds for each selected Node.js version, then do `prebuild --upload GITHUB_TOKEN` to upload those releases to GitHub.  Once this is done, you're pre-install script can indicate `prebuild --install`, and it will auto-download the appropriate GitHub files when applicable.

Here is an example of the `package.json` for one of my projects: 
https://github.com/couchbase/couchnode/blob/master/package.json#L45-L50

Cheers, Brett

**Comment by havenchyk** [comment]
Wow, that's awesome, thanks @brett19!

So, is it correct that I can use tools like travis or appveyor to automate the process?

**Comment by brett19** [comment]
Hey,
You can definitely use travis or appveyor to do your builds and have them uploaded to GitHub.  I don't think we have an example of that available at the moment though.
Cheers, Brett

**Comment by havenchyk** [comment]
Great, thanks for you help, really appreciate.

**Comment by ralphtheninja** [comment]
> Great, thanks for you help, really appreciate.

Let us know how things go!

**Comment by havenchyk** [comment]
@ralphtheninja I'm trying to make this module working with atom/electron, so to make this working I guess #61 should be implemented first, isn't it?

**Comment by ralphtheninja** [comment]
> @ralphtheninja I'm trying to make this module working with atom/electron, so to make this working I guess #61 should be implemented first, isn't it?

Correct. Maybe I should get started on a proposal so we can discuss how it should work.

**Comment by havenchyk** [comment]
Sure, it would be great if electron will be available in the `.prebuildrc` as well. As for other OS, I'll play around appveyor and travis to automate it. Thanks!
